export const browserCoreExamples = [
  "text2llm browser status",
  "text2llm browser start",
  "text2llm browser stop",
  "text2llm browser tabs",
  "text2llm browser open https://example.com",
  "text2llm browser focus abcd1234",
  "text2llm browser close abcd1234",
  "text2llm browser screenshot",
  "text2llm browser screenshot --full-page",
  "text2llm browser screenshot --ref 12",
  "text2llm browser snapshot",
  "text2llm browser snapshot --format aria --limit 200",
  "text2llm browser snapshot --efficient",
  "text2llm browser snapshot --labels",
];

export const browserActionExamples = [
  "text2llm browser navigate https://example.com",
  "text2llm browser resize 1280 720",
  "text2llm browser click 12 --double",
  'text2llm browser type 23 "hello" --submit',
  "text2llm browser press Enter",
  "text2llm browser hover 44",
  "text2llm browser drag 10 11",
  "text2llm browser select 9 OptionA OptionB",
  "text2llm browser upload /tmp/file.pdf",
  'text2llm browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "text2llm browser dialog --accept",
  'text2llm browser wait --text "Done"',
  "text2llm browser evaluate --fn '(el) => el.textContent' --ref 7",
  "text2llm browser console --level error",
  "text2llm browser pdf",
];
